### ISSUE TITLE
World coordinates scale

### ISSUE THREAD

**Issue by rjy219** [sz830/ProjectDayandNight#1]
For collision detection using the platforming engine, we need to check "a little" to the side of the player. I don't actually know how little "a little" is, nor have I figured out a way to automatically calculate such a figure. If anyone does know, go ahead and modify the value of the smallWorldUnit variable which I will be adding to Codebase_nightEngine/NYUCodebase/Engine.h in the nightEngine branch.

**Comment by sz830** [comment]
checking for collision should be done after moving the player either left
or right.
inside update, lets say the player moves Left
it goes
player.x+=player.velocityX*elapsed;
if(player's left side now is inside a wall)
 then a collision is detected

Shift the player's X position to the right side of the collision block +
.5*player.width.

...did you read the lecture notes?

The only time you should be checking a space outside of the player's
collision box is for jumping. In which you check slightly below the
player's bottom, by any arbitrary small amount.

**Comment by rjy219** [comment]
Sorry, I guess I wasn't clear enough. I wasn't clear on how coordinates were being  measured - I thought grid coordinates were in units of number of tiles, like 20x20, as opposed to the same scale as world coordinates. So I was just putting in numbers, guessing how far from the player's position I was supposed to be checking. Anyway, I've figured out that a length based directly off the player's hitbox dimensions is probably best.
